# O LOOP WHILE, DIFERENTEMENTE DO LOOP FOR, REPETE UMA ORDEM DE COMANDOS ENQUANTO A CONDIÇÃO NÃO É ATENDIDA

numero = 1 #VARIÁVEL NÚMERO COM VALOR DEFAULT 1 

while numero < 20: #ENQUANTO NUMERO FOR MENOR QUE 20
    print(numero) #EXIBE O VALOR ATUAL DA VARIÁVEL NÚMERO
    numero = numero + 1 # INCREMENTA +1 AO CONTADOR NUMÉRICO