#O LOOP FOR É UTILIZADO PARA REALIZAR UMA REPETIÇÃO DE COMANDOS PARA CADA ITERADOR (ITEM) DE UMA DETERMINADA LISTA/CONJUNTO DE DADOS

lista = [1, 2, 3, 4, 5] #VARIÁVEL LISTA COM OS VALORES ARMZENADOS

for i in lista: #PARA CADA ITEM DA LISTA - RECEBA "i" COMO ITEM
    print(i) #EXIBE VALOR ATUAL NA REPETIÇÃO DO LOOP